#!/usr/bin/python3

import argparse
import logging
import logging.handlers
import os
import re
import sys
import time

from aprs2mqtt import MQTT2APRS

if __name__ == "__main__":
    # get the options from the CLI
    ap = argparse.ArgumentParser(description="Listen to MQTT for APRS MSGs to send")
    ap.add_argument("--broker", help="the MQTT broker FQDN or IP", required=True)
    ap.add_argument("--user", help="the username for the MQTT broker")
    ap.add_argument("--passwd", help="the password for the MQTT broker")
    ap.add_argument("--topic", help="the MQTT topic", required=True)
    ap.add_argument("--tls", help="use TLS for the MQTT connection", action="store_true")
    ap.add_argument("--queuedir",
        help="path to the KISS message queue (default=/var/aprs/queue)",
        default="/var/aprs/queue",
    )
    ap.add_argument("--debug", help="enable debug-level logging in syslog", action="store_true")
    args = ap.parse_args()

    # setup logging
    log = logging.getLogger("mqtt2aprsmsg")
    lh = logging.handlers.SysLogHandler(address = "/dev/log", facility="daemon")
    lf = logging.Formatter(fmt='%(name)s: %(levelname)s: %(message)s')
    lh.setFormatter(lf)
    log.addHandler(lh)

    if args.debug:
        log.setLevel(logging.DEBUG)
    else:
        log.setLevel(logging.INFO)

    try:
        log.debug("inside main try to setup client")

        if args.tls:
            log.debug("using TLS due to --tls")
            usetls = True
        else:
            usetls = False

        m2a = MQTT2APRS.MQTT2APRS(args.broker, args.username, args.passwd, usetls)

        if args.queuedir is not None:
            m2a.queuedir = args.queuedir
        
        m2a.topic = args.topic
        m2a.start()
        m2a.loop()

    except KeyboardInterrupt:
        try:
            log.debug("exiting on interrupt")
            m2a.stop()
            sys.exit(0)
        except SystemExit:
            os._exit(0)

    except Exception as e:
        if str(e).find("getaddrinfo failed") > -1:
            log.error("hostname not found; exiting")
            sys.exit("Error: unknown hostname")
        log.error("quitting with general error: " + str(e))    
        sys.exit("Error: " + str(e))
